const SHEET_ID='1m1xkYCMDxbFEHTDsqz_BkrJjjaoSSMrU';
const SHEET_NAME='Main (2)';
const CSV_URL=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(SHEET_NAME)}`;
let DATA=[], COL={}, charts={};
const $=id=>document.getElementById(id);
const norm=s=>String(s??'').toLowerCase().replace(/[^a-z0-9]/g,'');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));

function parseCSV(text){let rows=[],row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'){if(q&&n==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(v=>v!==''))rows.push(row);row=[]}else cell+=c}row.push(cell);if(row.some(v=>v!==''))rows.push(row);return rows}
function findCol(headers,aliases){const hs=headers.map(norm);for(const a of aliases){const i=hs.indexOf(norm(a));if(i>=0)return headers[i]}for(let i=0;i<hs.length;i++)if(aliases.some(a=>hs[i].includes(norm(a))))return headers[i];return null}
function isoWeek(value){if(!value)return'';const d=new Date(value);if(isNaN(d))return'';const t=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));t.setUTCDate(t.getUTCDate()+4-(t.getUTCDay()||7));const y=new Date(Date.UTC(t.getUTCFullYear(),0,1));return `W${String(Math.ceil((((t-y)/86400000)+1)/7)).padStart(2,'0')}`}
function countBy(rows,key){const o={};if(!key)return o;rows.forEach(r=>{const v=(r[key]??'').toString().trim()||'Blank';o[v]=(o[v]||0)+1});return o}
function topEntry(o){return Object.entries(o).sort((a,b)=>b[1]-a[1])[0]||['—',0]}
function unique(rows,key){return key?new Set(rows.map(r=>r[key]).filter(Boolean)).size:rows.length}
function setOptions(id,values){const el=$(id),cur=el.value;el.innerHTML=`<option value="ALL">All</option>`;[...new Set(values.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true})).forEach(v=>el.insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(v)}</option>`));if([...el.options].some(o=>o.value===cur))el.value=cur}
function filtered(){const q=$('search').value.toLowerCase(),w=$('week').value,a=$('activity').value,s=$('status').value;return DATA.filter(r=>(w==='ALL'||r.__week===w)&&(a==='ALL'||(COL.activity&&r[COL.activity]===a))&&(s==='ALL'||(COL.status&&r[COL.status]===s))&&(!q||Object.values(r).join(' ').toLowerCase().includes(q)))}
function chart(id,type,labels,values,label){if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),{type,data:{labels,datasets:[{label,data:values,borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:type==='doughnut'}},scales:type==='doughnut'?{}:{y:{beginAtZero:true,ticks:{precision:0}},x:{ticks:{maxRotation:45,minRotation:0}}}}})}
function render(){const rows=filtered();$('total').textContent=rows.length.toLocaleString();$('visits').textContent=unique(rows,COL.visit).toLocaleString();
 const wc=countBy(rows,'__week');const weeks=Object.keys(wc).filter(x=>x!=='Blank').sort((a,b)=>parseInt(a.replace(/\D/g,''))-parseInt(b.replace(/\D/g,'')));const lw=weeks.at(-1)||'—';$('latestWeek').textContent=lw;$('latestWeekCount').textContent=lw==='—'?'No week/date column detected':`${wc[lw]} records`;
 const [ta,tac]=topEntry(countBy(rows,COL.activity));$('topActivity').textContent=ta;$('topActivityCount').textContent=tac?`${tac} records`:COL.activity?'No activity data':'No activity column detected';
 chart('weekChart','bar',weeks,weeks.map(w=>wc[w]),'Records');const ac=countBy(rows,COL.activity);const ae=Object.entries(ac).sort((a,b)=>b[1]-a[1]).slice(0,10);chart('activityChart','doughnut',ae.map(x=>x[0]),ae.map(x=>x[1]),'Records');const sc=countBy(rows,COL.status);const se=Object.entries(sc).sort((a,b)=>b[1]-a[1]).slice(0,10);chart('statusChart','doughnut',se.map(x=>x[0]),se.map(x=>x[1]),'Records');const vc=countBy(rows,COL.vessel||COL.visit);const ve=Object.entries(vc).sort((a,b)=>b[1]-a[1]).slice(0,10);chart('vesselChart','bar',ve.map(x=>x[0]),ve.map(x=>x[1]),'Records');
 renderInsights(rows,weeks,wc,ta,tac);renderTable(rows)}
function renderInsights(rows,weeks,wc,ta,tac){let a=[];if(weeks.length>=2){const c=wc[weeks.at(-1)]||0,p=wc[weeks.at(-2)]||0,d=p?((c-p)/p*100):0;a.push(`<div class="insight"><b>${esc(weeks.at(-1))}: ${c} records</b><span>${p?`${d>=0?'+':''}${d.toFixed(1)}% vs ${esc(weeks.at(-2))}`:'Previous week has no records'}</span></div>`)}else a.push(`<div class="insight"><b>${rows.length} records loaded</b><span>More weeks will improve trend analysis.</span></div>`);if(ta!=='—')a.push(`<div class="insight"><b>${esc(ta)}</b><span>Largest activity/reason: ${tac} records (${rows.length?(tac/rows.length*100).toFixed(1):0}%).</span></div>`);if(COL.status){const [st,n]=topEntry(countBy(rows,COL.status));a.push(`<div class="insight"><b>${esc(st)}</b><span>Most common status: ${n} records (${rows.length?(n/rows.length*100).toFixed(1):0}%).</span></div>`)}if(COL.vessel){const [v,n]=topEntry(countBy(rows,COL.vessel));a.push(`<div class="insight"><b>${esc(v)}</b><span>Most frequent vessel/item: ${n} records.</span></div>`)}$('insights').innerHTML=a.join('')}
function renderTable(rows){const headers=Object.keys(DATA[0]||{}).filter(h=>!h.startsWith('__'));const show=headers.slice(0,14);$('thead').innerHTML='<tr>'+show.map(h=>`<th>${esc(h)}</th>`).join('')+'</tr>';$('tbody').innerHTML=rows.slice(0,500).map(r=>'<tr>'+show.map(h=>`<td>${esc(r[h])}</td>`).join('')+'</tr>').join('');$('countLabel').textContent=`${rows.length.toLocaleString()} records${rows.length>500?' • showing first 500':''}`}
async function load(){try{$('sourceStatus').textContent='Connecting to Main (2)…';$('dot').className='dot';$('errorBox').classList.add('hidden');const res=await fetch(CSV_URL,{cache:'no-store'});if(!res.ok)throw new Error(`Google Sheet returned HTTP ${res.status}`);const text=await res.text();if(text.trim().startsWith('<!DOCTYPE')||text.includes('accounts.google.com'))throw new Error('The sheet is not publicly readable. Set General access to “Anyone with the link – Viewer”.');const matrix=parseCSV(text);if(matrix.length<2)throw new Error('Main (2) returned no data rows.');const headers=matrix[0].map((h,i)=>h.trim()||`Column ${i+1}`);DATA=matrix.slice(1).map(row=>Object.fromEntries(headers.map((h,i)=>[h,row[i]??''])));
 COL={visit:findCol(headers,['Visit No','Visit Number','Visit','VCN']),vessel:findCol(headers,['Vessel Name','Vessel','Ship Name']),activity:findCol(headers,['Visit Reason','Activity','Reason','VisitReasonCode']),status:findCol(headers,['Status','Sign Off Status']),week:findCol(headers,['Week No','Week Number','Week']),date:findCol(headers,['Date','Arrival Date','Start Date','ATA','Estimated Time Arrival'])};DATA.forEach(r=>r.__week=COL.week?(String(r[COL.week]).match(/\d+/)?`W${String(r[COL.week]).match(/\d+/)[0].padStart(2,'0')}`:r[COL.week]):isoWeek(r[COL.date]));setOptions('week',DATA.map(r=>r.__week));setOptions('activity',COL.activity?DATA.map(r=>r[COL.activity]):[]);setOptions('status',COL.status?DATA.map(r=>r[COL.status]):[]);$('sourceStatus').textContent='Live data connected';$('dot').className='dot ok';$('updated').textContent=`Updated ${new Date().toLocaleString('en-MY')}`;render()}catch(e){$('sourceStatus').textContent='Data connection needs attention';$('dot').className='dot bad';$('errorBox').classList.remove('hidden');$('errorBox').innerHTML=`<b>Unable to read Main (2).</b><br>${esc(e.message)}<br><br>Source URL is already configured. Once the Google Sheet is shared for viewing, press <b>Refresh data</b>.`;$('insights').innerHTML='<div class="insight"><b>Waiting for Google Sheet access</b><span>The webpage itself is deployed and ready.</span></div>'}}
['search','week','activity','status'].forEach(id=>$(id).addEventListener('input',()=>DATA.length&&render()));$('reset').onclick=()=>{['week','activity','status'].forEach(id=>$(id).value='ALL');$('search').value='';if(DATA.length)render()};$('refresh').onclick=load;load();