-- PTP Pilot Allocation System - Supabase/PostgreSQL schema
create table if not exists pilots (
 id bigint generated by default as identity primary key,
 code text unique not null, pilot_class text, licence text, group_code text, status text default 'Active',
 created_at timestamptz default now()
);
create table if not exists vessels (
 id bigint generated by default as identity primary key,
 plan_date date not null, shift_type text not null, vessel_name text not null, loa text, wharf_mark text,
 bunker text, book_time text, clearance_minutes integer, to_loa text, to_wharf_mark text, to_vessel_name text,
 remarks text, row_color text, is_special boolean default false, created_at timestamptz default now()
);
create table if not exists allocations (
 id bigint generated by default as identity primary key,
 plan_date date not null, shift_type text not null, pilot_code text not null, slot_no integer not null,
 allocation_code text, updated_at timestamptz default now(),
 unique(plan_date,shift_type,pilot_code,slot_no)
);
create table if not exists allocation_history (
 id bigint generated by default as identity primary key,
 plan_date date not null, shift_type text not null, snapshot jsonb not null, created_at timestamptz default now()
);
create table if not exists app_config (
 config_key text primary key, config_value jsonb not null, updated_at timestamptz default now()
);
alter table pilots enable row level security;
alter table vessels enable row level security;
alter table allocations enable row level security;
alter table allocation_history enable row level security;
alter table app_config enable row level security;
-- Replace these demo policies with authenticated-user policies before production.
create policy "demo pilots all" on pilots for all using (true) with check (true);
create policy "demo vessels all" on vessels for all using (true) with check (true);
create policy "demo allocations all" on allocations for all using (true) with check (true);
create policy "demo history all" on allocation_history for all using (true) with check (true);
create policy "demo config all" on app_config for all using (true) with check (true);
